=begin

This file is part of the CoYoHo Control Your Home System.

Copyright 2011-2012 Dirk Grappendorf, www.grappendorf.net

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=end

source "http://rubygems.org"

gem 'ruby-debug-ide', '>=0.4.16'
gem 'rake', '>=0.9.2.2'
gem 'jruby-openssl', '~>0.7.6.1'
gem 'rufus-scheduler', '~>2.0.16'
gem 'thread_storm', '~>0.7.1'
gem 'statemachine', '~>2.0.1'
gem 'logging', '~>1.7.2'
gem 'micon', '~>0.1.28'
gem 'grape', '~>0.2.1', git: 'https://github.com/intridea/grape'
gem 'renum', '~>1.3.1'
gem 'defined', '~>0.0.2'
gem 'rubydin', '~>6.8.0.1'
gem 'rubydin-optional-di', '~>6.8.0.1'
gem 'rubydin-optional-datamapper', '~>6.8.0.1'
gem 'rubydin-optional-standalone', '~>6.8.0.1'
gem 'rubydin-addons-codemirror', '~>2.2.4.1'
gem 'rubydin-addons-confirmdialog', '~>1.2.0.1'
gem 'rubydin-addons-console', '~>1.1.6.1'
gem 'rubydin-addons-serverpush', '~>1.0.6.1'
gem 'rubydin-addons-colorpicker', '~>1.1.0.1'
gem 'rubydin-addons-wizardsforvaadin', '~>0.4.4.1'
gem 'rspec', '>=2.10.0'
gem 'simplecov', '>=0.6.4'
gem 'cucumber', '>=1.2.1'
gem 'capybara', '>=1.1.2'
gem 'factory_girl', '>=3.2.0'
gem 'database_cleaner', '>=0.8.0'
#gem 'machinist', '>=2.0'
#gem 'dm-machinist', '>=0.0.1'

gem 'virtus', '~>0.5'
gem 'dm-core', '1.3.0.beta', git: 'https://github.com/datamapper/dm-core'
gem 'dm-active_model', '1.3.0.beta', git: 'https://github.com/datamapper/dm-active_model.git'
gem 'dm-validations', '1.3.0.beta', git: 'https://github.com/datamapper/dm-validations.git'
gem 'dm-rails', '1.3.0.beta', git: 'https://github.com/datamapper/dm-rails.git'
gem 'dm-migrations', '1.3.0.beta', git: 'https://github.com/datamapper/dm-migrations'
gem 'dm-types', '1.3.0.beta', git: 'https://github.com/datamapper/dm-types'
gem 'dm-constraints', '1.3.0.beta', git: 'https://github.com/datamapper/dm-constraints'
gem 'dm-transactions', '1.3.0.beta', git: 'https://github.com/datamapper/dm-transactions'
gem 'dm-aggregates', '1.3.0.beta', git: 'https://github.com/datamapper/dm-aggregates'
gem 'dm-timestamps', '1.3.0.beta', git: 'https://github.com/datamapper/dm-timestamps'
gem 'dm-observer', '1.3.0.beta', git: 'https://github.com/datamapper/dm-observer'
gem 'dm-serializer', '1.3.0.beta', git: 'https://github.com/datamapper/dm-serializer'
gem 'dm-do-adapter', '1.3.0.beta', git: 'https://github.com/datamapper/dm-do-adapter'
gem 'dm-postgres-adapter', '1.3.0.beta', git: 'https://github.com/datamapper/dm-postgres-adapter'
gem 'dm-sqlite-adapter', '1.3.0.beta', git: 'https://github.com/datamapper/dm-sqlite-adapter'
gem 'data_mapper', '1.3.0.beta', git: 'https://github.com/datamapper/data_mapper'
